# Generated by Django 5.1.3 on 2024-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ExamManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='passing_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
